name: usercentrics_sdk
description: The Usercentrics Apps SDK is a Consent Management Platform framework that ensures legal compliance for different legal frameworks.
homepage: https://usercentrics.com
documentation: https://docs.usercentrics.com/cmp_in_app_sdk/
repository: https://github.com/Usercentrics/flutter-sdk/

# Update version process:
#  [X] pubspec.yaml
#  [X] android/build.gradle
#  [X] ios/usercentrics_sdk.podspec + pod install/update
#  [X] CHANGELOG
version: 2.2.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  test: ^1.17.10

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  plugin:
    platforms:
      android:
        package: com.usercentrics.sdk.flutter
        pluginClass: UsercentricsPlugin
      ios:
        pluginClass: UsercentricsPlugin
