name: usercentrics_sdk
description: Usercentrics Flutter SDK.
version: 2.0.1
homepage: https://docs.usercentrics.com/#/in-app-sdk

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  test: 1.18.2

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  plugin:
    platforms:
      android:
        package: com.usercentrics.sdk.flutter
        pluginClass: UsercentricsPlugin
      ios:
        pluginClass: UsercentricsPlugin
