import 'package:usercentrics_sdk/src/model/labels.dart';

class LabelsSerializer {
  static UsercentricsLabels deserialize(dynamic value) {
    return UsercentricsLabels(
      btnAcceptAll: value['btnAcceptAll'] ?? "",
      btnDeny: value['btnDeny'] ?? "",
      btnSave: value['btnSave'] ?? "",
      firstLayerTitle: value['firstLayerTitle'] ?? "",
      accepted: value['accepted'] ?? "",
      denied: value['denied'] ?? "",
      date: value['date'] ?? "",
      decision: value['decision'] ?? "",
      dataCollectedList: value['dataCollectedList'] ?? "",
      dataCollectedInfo: value['dataCollectedInfo'] ?? "",
      locationOfProcessing: value['locationOfProcessing'] ?? "",
      transferToThirdCountries: value['transferToThirdCountries'] ?? "",
      dataPurposes: value['dataPurposes'] ?? "",
      dataPurposesInfo: value['dataPurposesInfo'] ?? "",
      dataRecipientsList: value['dataRecipientsList'] ?? "",
      descriptionOfService: value['descriptionOfService'] ?? "",
      history: value['history'] ?? "",
      historyDescription: value['historyDescription'] ?? "",
      legalBasisList: value['legalBasisList'] ?? "",
      legalBasisInfo: value['legalBasisInfo'] ?? "",
      processingCompanyTitle: value['processingCompanyTitle'] ?? "",
      technologiesUsed: value['technologiesUsed'] ?? "",
      technologiesUsedInfo: value['technologiesUsedInfo'] ?? "",
      cookiePolicyInfo: value['cookiePolicyInfo'] ?? "",
      optOut: value['optOut'] ?? "",
      policyOf: value['policyOf'] ?? "",
      imprintLinkText: value['imprintLinkText'] ?? "",
      privacyPolicyLinkText: value['privacyPolicyLinkText'] ?? "",
      categories: value['categories'] ?? "",
      anyDomain: value['anyDomain'] ?? "",
      day: value['day'] ?? "",
      days: value['days'] ?? "",
      domain: value['domain'] ?? "",
      duration: value['duration'] ?? "",
      informationLoadingNotPossible:
          value['informationLoadingNotPossible'] ?? "",
      hour: value['hour'] ?? "",
      hours: value['hours'] ?? "",
      identifier: value['identifier'] ?? "",
      maximumAgeCookieStorage: value['maximumAgeCookieStorage'] ?? "",
      minute: value['minute'] ?? "",
      minutes: value['minutes'] ?? "",
      month: value['month'] ?? "",
      months: value['months'] ?? "",
      multipleDomains: value['multipleDomains'] ?? "",
      no: value['no'] ?? "",
      nonCookieStorage: value['nonCookieStorage'] ?? "",
      seconds: value['seconds'] ?? "",
      session: value['session'] ?? "",
      loadingStorageInformation: value['loadingStorageInformation'] ?? "",
      storageInformation: value['storageInformation'] ?? "",
      detailedStorageInformation: value['detailedStorageInformation'] ?? "",
      tryAgain: value['tryAgain'] ?? "",
      type: value['type'] ?? "",
      year: value['year'] ?? "",
      years: value['years'] ?? "",
      yes: value['yes'] ?? "",
      storageInformationDescription:
          value['storageInformationDescription'] ?? "",
      btnBannerReadMore: value['btnBannerReadMore'] ?? "",
      btnMore: value['btnMore'] ?? "",
      linkToDpaInfo: value['linkToDpaInfo'] ?? "",
      second: value['second'] ?? "",
      consent: value['consent'] ?? "",
      secondLayerDescriptionHtml: value['secondLayerDescriptionHtml'] ?? "",
      secondLayerTitle: value['secondLayerTitle'] ?? "",
      retentionPeriod: value['retentionPeriod'] ?? "",
    );
  }
}
